name: Build
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - run: git checkout -b "ci/$GITHUB_REF"
      - if: github.event_name == 'pull_request'
        run: git remote set-url origin ${{ github.event.pull_request.head.repo.git_url }}
      - run: |
          echo ${{ github.run_id }} > run_id.txt
          git add run_id.txt
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git commit -m 'Workflow run ${{ github.run_id }}'
          git push -f origin HEAD
